version: '3'
services:
  gateway: 
    image: ex3-api-microservice
    ports:
      - 4001:4001
    environment:
      - PORT=4001
      - DB_HOST=127.0.0.1
      - DB_PORT=5432
      - DB_USERNAME=test
      - DB_PASSWORD=Niyas123
      - DB_DATABASE=test_typeorm
      - BROKER_URL=http://127.0.0.1:5672